### PR TITLE
[1.12.2] Fix crash if traceResult is null

### PR DESCRIPTION
**Pull request by KorDum**
Fix for crash
https://gist.githubusercontent.com/KorDum/828986e927ed50c5918277a141a0ffec/raw/a3ae6162fdd27b140b36c34f2d47dad3b4e0510f/gistfile1.txt

### CODE REVIEW

**Comment by KingLemming** [comment]
If the traceResult is null, something has gone *very* wrong in the world. It should never return a null.

**Comment by covers1624** [comment]
Null is a valid case for raytracing, There are several cases inside world.rayTraceBlocks that can return null. This should be pulled.

**Comment by KingLemming** [comment]
I don't agree, actually. The base method should be fixed to not return null if that's the case.

**Comment by KingLemming** [comment]
I've handled this in a number of places, not just this one. Adjusted a bit of logic on the way as well.

Thanks for bringing it to our attention. :)

**Pull request closed without merging**
