### PR TITLE
Add counting to ItemFilter

### PR DESCRIPTION
**Pull request by Knugel**
Allows ItemFilter to filter on stack size.

### CODE REVIEW

**Comment by KingLemming** [comment]
I think I see where you're going with this, but I feel this is potentially a very awkward mechanic.

I would like to add a filter to the Item Allocator, but I'm not sure that adding "count" as a filter field is quite the right way to handle it.

**Comment by Knugel** [comment]
The filter for the Item Allocator is why I needed the counting flag. I'm not sure how to handle this better without just duplicating a lot of the filter logic.

Altough I can see how it would be a little awkard when it comes to moving sets as it currently only matches the exact count.

**Comment by KingLemming** [comment]
I had planned on adding a "Move exact quantity" option to the allocator itself, and then the filter would simply be a bonus option.

I think putting it on the filter may overcomplicate it.

**Comment by Knugel** [comment]
I'm not sure how the configuring of the individual quantities would work then. Would there be only one amount for all nine slots?.

 The filter seemed to be the easiest / most consistent way to configure this to me.

**Comment by KingLemming** [comment]
It would be, yes. I can see how that's also not ideal. So ehh...

**Pull request closed without merging**
